<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Word press" duration-ms="12766" started-at="2020-11-03T05:27:57Z" finished-at="2020-11-03T05:28:09Z">
    <groups>
    </groups>
    <test name="Run on Firefox" duration-ms="12766" started-at="2020-11-03T05:27:57Z" finished-at="2020-11-03T05:28:09Z">
      <class name="com.wordpress.media.Media_01_uploadFile">
        <test-method status="PASS" signature="beforeClass(java.lang.String)[pri:0, instance:com.wordpress.media.Media_01_uploadFile@5442a311]" name="beforeClass" is-config="true" duration-ms="7237" started-at="2020-11-03T12:27:57Z" finished-at="2020-11-03T12:28:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="TC_01_LoginSuccessAndGoToDashboardFC()[pri:0, instance:com.wordpress.media.Media_01_uploadFile@5442a311]" name="TC_01_LoginSuccessAndGoToDashboardFC" duration-ms="5509" started-at="2020-11-03T12:28:04Z" finished-at="2020-11-03T12:28:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Stats and Insights] but found [Let's get your site a domain!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Stats and Insights] but found [Let's get your site a domain!]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.wordpress.media.Media_01_uploadFile.TC_01_LoginSuccessAndGoToDashboardFC(Media_01_uploadFile.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_LoginSuccessAndGoToDashboardFC -->
        <test-method status="FAIL" signature="TC_02_uploadMultipleFile()[pri:0, instance:com.wordpress.media.Media_01_uploadFile@5442a311]" name="TC_02_uploadMultipleFile" duration-ms="1" started-at="2020-11-03T12:28:09Z" finished-at="2020-11-03T12:28:09Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.wordpress.media.Media_01_uploadFile.TC_02_uploadMultipleFile(Media_01_uploadFile.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_02_uploadMultipleFile -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.wordpress.media.Media_01_uploadFile@5442a311]" name="afterClass" is-config="true" duration-ms="0" started-at="2020-11-03T12:28:09Z" finished-at="2020-11-03T12:28:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.wordpress.media.Media_01_uploadFile -->
    </test> <!-- Run on Firefox -->
  </suite> <!-- Word press -->
</testng-results>
